### ISSUE TITLE
Setting TextPaint has no effect

### ISSUE THREAD

**Issue by danielbanks** [amlcurran/ShowcaseView#361]
I create a text paint variable as per the sample
```
Typeface typeface = Typeface.createFromAsset(activity.getAssets(), "fonts/Vollkorn-Regular.otf");
paint = new TextPaint(Paint.ANTI_ALIAS_FLAG);
paint.setTypeface(typeface);
paint.setTextAlign(Paint.Align.LEFT);
```

I then set this to my current showcase view

```
currentView` =  new ShowcaseView.Builder(activity).setTarget(new ViewTarget(properties.getTargetView()))
   .blockAllTouches()
   .setStyle(R.style.Tutorial)
   .setContentTitlePaint(paint)
   .setContentTitle(properties.getMsg())
   .replaceEndButton(newButton)
   .build();
```

However the result is I see no change in the font from androids default.

**Comment by amlcurran** [comment]
Whoops! I'll take a look

**Comment by amlcurran** [comment]
Hi @danielbanks, I can't seemingly reproduce this. What version of the library are you using, and on what devices/Android versions?

**Comment by Saudasadaf** [comment]
Even I'm not able to set text paint , library is 5.4.0

**Comment by danielbanks** [comment]
@amlcurran Library is 5.4.0 and we tested mainly on A samsung s5 (G900P) running android 5.0

**Comment by amlcurran** [comment]
Using the latest sample app on an S4 running 5.0.1 works fine. Could you see if the "Custom Text" sample looks the same for you on your device? The sample app is available from [Google Play](https://play.google.com/store/apps/details?id=com.espian.showcaseview.sample) or as an [APK](https://github.com/amlcurran/ShowcaseView/releases/download/5.4.0/sample-release.apk)

**Comment by amlcurran** [comment]
Found the issue!

**Comment by amlcurran** [comment]
This should be fixed as of version 5.4.1 which I just released, can you please check that fixes your problem?

**Comment by danielbanks** [comment]
This has not completely fixed my issue. I can setStrikeThruTest to true and see the strike through, I can also change the text alignment, but changing the typeface or the colour have no effect. However  I can change the text colour using a custom style, so the main issue is being able to change the typeface.

**Comment by amlcurran** [comment]
@danielbanks and what about the demo app, does that work correctly on your device? That uses a custom typeface.

**Comment by danielbanks** [comment]
@amlcurran Yep the demo app works fine. I also downloaded the demo app font and tried to apply that, but there was no change.

**Comment by amlcurran** [comment]
Sorry I haven't replied! So the typeface isn't working? Are you using Calligraphy or any other library which changes the font?

**Comment by VisheshVadhera** [comment]
@amlcurran, facing the same issue. TextPaint has no effect on the text of the showcase. Tried doing this:

```
TextPaint textPaint = new TextPaint(Paint.ANTI_ALIAS_FLAG);
textPaint.setColor(Color.YELLOW);
textPaint.setTextSize(activity.getResources().getDimension(R.dimen.showcase_size));
textPaint.setTypeface(Typeface.createFromAsset(activity.getAssets(), "RobotoSlab-Regular.ttf"));
```

which didn't really change the text at all, though in the sample app it seems to be working fine. And yes I am indeed using Caligraphy to change the fonts. You think that might be the reason?

**Comment by yelsane** [comment]
Experience this as well, but managed to make it work.

I was initially setting all the styles via `styles.xml` and setting it in the builder. The font doesn't seem to work when you set it from the xml. Tried the `TextPaint` fix, but didn't work initially -- the reason was because I was still setting the style when building the ShowcaseView. Removed the corresponding `sv_titleTextAppearance` and `sv_detailTextAppearance` in the styles, then moved the `.setStyle` in builder first before setting the paints like so:

```
final ShowcaseView sv = new ShowcaseView.Builder(this)
                    .setTarget(new ViewTarget(tab))
                    .setStyle(R.style.CustomShowcaseTheme)
                    .setContentTitle(getString(R.string.title))
                    .setContentTitlePaint(titlePaint)
                    .setContentText(getString(R.string.description))
                    .setContentTextPaint(descriptionPaint)
                    .singleShot(1L)
                    .build();
```

Font specified worked as expected. My guess is that calling `.setStyle()` after `.setContentTitlePaint()` and `.setContentTextPaint()` overrides the values and sets it to default.
